[package]
name = "influxdb3_replication_protos"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.11"
prost = "0.12"
# Required for generated code by tonic/prost
bytes = "1"
prost-types = "0.12"


[build-dependencies]
tonic-build = { version = "0.11", features = ["prost"] }
